from alembic import op
import sqlalchemy as sa
from app import Base  # Import your Base from your application
target_metadata = Base.metadata


# Revision identifiers, used by Alembic.
revision = 'your_revision_id'
down_revision = 'previous_revision_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'email', new_column_name='title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'title', new_column_name='email')
    # ### end Alembic commands ###
